//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssistantTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssistantTbl()
        {
            this.Assistan_ProjectTbl = new HashSet<Assistan_ProjectTbl>();
            this.ProfessorTbl = new HashSet<ProfessorTbl>();
        }
    
        public int AssistantID { get; set; }
        public string AssistantName { get; set; }
        public string AssistantSurname { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string AssistantPhoto { get; set; }
        public Nullable<int> AssignProject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assistan_ProjectTbl> Assistan_ProjectTbl { get; set; }
        public virtual ProjectTbl ProjectTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorTbl> ProfessorTbl { get; set; }
    }
}
