//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysTable
    {
        public int Total { get; set; }
        public Nullable<int> JuryID { get; set; }
        public string AvaibilityInfo { get; set; }
        public int DayNumber { get; set; }
    
        public virtual JuriesTbl JuriesTbl { get; set; }
    }
}
