//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTbl
    {
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string OfficeNumber { get; set; }
        public int AssignFaculty { get; set; }
        public string OfficePhoneNumber { get; set; }
    
        public virtual FacultyTbl FacultyTbl { get; set; }
    }
}
