//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeTbl
    {
        public int GradeID { get; set; }
        public int AssignFaculty { get; set; }
        public int AssignStudent { get; set; }
        public string LetterGrade { get; set; }
        public int AverageGrade { get; set; }
        public int FirstNumericalGrade { get; set; }
        public int SecondNumericalGrade { get; set; }
        public int ThirdNumericalGrade { get; set; }
    
        public virtual FacultyTbl FacultyTbl { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
