//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_ProjectTbl
    {
        public int Group_ProjectID { get; set; }
        public int AssignGroupID { get; set; }
        public int AssignProjectID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual GroupTbl GroupTbl { get; set; }
        public virtual ProjectTbl ProjectTbl { get; set; }
    }
}
