//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuriesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JuriesTbl()
        {
            this.DaysTable = new HashSet<DaysTable>();
        }
    
        public int JuryID { get; set; }
        public string JuryName { get; set; }
        public Nullable<int> DateInfo { get; set; }
        public Nullable<int> AvabilityInfo { get; set; }
        public Nullable<int> AssignProjectID { get; set; }
        public Nullable<int> AssignVoteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaysTable> DaysTable { get; set; }
    }
}
