//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileAppTbl
    {
        public int VoteId { get; set; }
        public string VoteTitle { get; set; }
        public string VoteDescription { get; set; }
        public int Rating { get; set; }
        public System.DateTime VoteStartDate { get; set; }
        public System.DateTime VoteEndDate { get; set; }
        public Nullable<int> AssignProfessor { get; set; }
        public int VoteStatus { get; set; }
    }
}
