//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GraduationProjectManagementDBEntities : DbContext
    {
        public GraduationProjectManagementDBEntities()
            : base("name=GraduationProjectManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnouncementTbl> AnnouncementTbl { get; set; }
        public virtual DbSet<Assistan_ProjectTbl> Assistan_ProjectTbl { get; set; }
        public virtual DbSet<AssistantTbl> AssistantTbl { get; set; }
        public virtual DbSet<DaysTable> DaysTable { get; set; }
        public virtual DbSet<DepartmentTbl> DepartmentTbl { get; set; }
        public virtual DbSet<FacultyTbl> FacultyTbl { get; set; }
        public virtual DbSet<FeedbackTbl> FeedbackTbl { get; set; }
        public virtual DbSet<GradeTbl> GradeTbl { get; set; }
        public virtual DbSet<Group_ProjectTbl> Group_ProjectTbl { get; set; }
        public virtual DbSet<GroupRatingResultTbl> GroupRatingResultTbl { get; set; }
        public virtual DbSet<GroupTbl> GroupTbl { get; set; }
        public virtual DbSet<JuriesTbl> JuriesTbl { get; set; }
        public virtual DbSet<Jury_GroupTbl> Jury_GroupTbl { get; set; }
        public virtual DbSet<Jury_ProfessorTbl> Jury_ProfessorTbl { get; set; }
        public virtual DbSet<MobileAppTbl> MobileAppTbl { get; set; }
        public virtual DbSet<PresentationsTbl> PresentationsTbl { get; set; }
        public virtual DbSet<Professor_ProjectTbl> Professor_ProjectTbl { get; set; }
        public virtual DbSet<ProfessorTbl> ProfessorTbl { get; set; }
        public virtual DbSet<ProjectTbl> ProjectTbl { get; set; }
        public virtual DbSet<QuestionTbl> QuestionTbl { get; set; }
        public virtual DbSet<Student_GroupTbl> Student_GroupTbl { get; set; }
        public virtual DbSet<Student_ProjectTbl> Student_ProjectTbl { get; set; }
        public virtual DbSet<StudentTbl> StudentTbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaskTbl> TaskTbl { get; set; }
        public virtual DbSet<TurnitinTbl> TurnitinTbl { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VoteTbl> VoteTbl { get; set; }
    }
}
