//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentationsTbl
    {
        public int PresentationID { get; set; }
        public string ProjectName { get; set; }
        public int PresentationDate { get; set; }
        public int MinuteInfo { get; set; }
        public string AssignJuryID { get; set; }
        public int AssignGroupID { get; set; }
    
        public virtual GroupTbl GroupTbl { get; set; }
    }
}
