//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor_ProjectTbl
    {
        public int Professor_ProjectID { get; set; }
        public int ProfessorID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual ProfessorTbl ProfessorTbl { get; set; }
        public virtual ProjectTbl ProjectTbl { get; set; }
    }
}
