//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessorTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessorTbl()
        {
            this.Professor_ProjectTbl = new HashSet<Professor_ProjectTbl>();
            this.StudentTbl = new HashSet<StudentTbl>();
        }
    
        public int ProfessorID { get; set; }
        public string ProfessorUsername { get; set; }
        public string ProfessorName { get; set; }
        public string ProfessorSurname { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string ProfessorPrerequisites { get; set; }
        public string ProfessorPhoto { get; set; }
        public string UploadFile { get; set; }
        public Nullable<int> AssignAssistan { get; set; }
        public Nullable<int> AssignFaculty { get; set; }
        public Nullable<int> AssignProject { get; set; }
    
        public virtual AssistantTbl AssistantTbl { get; set; }
        public virtual FacultyTbl FacultyTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor_ProjectTbl> Professor_ProjectTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTbl> StudentTbl { get; set; }
    }
}
