//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_ProjectTbl
    {
        public int Student_ProjectID { get; set; }
        public int StudentID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ProjectTbl ProjectTbl { get; set; }
        public virtual ProjectTbl ProjectTbl1 { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
