//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnitinTbl
    {
        public int TurnitinID { get; set; }
        public Nullable<int> AssignGroup { get; set; }
        public string TurnitinResult { get; set; }
    
        public virtual GroupTbl GroupTbl { get; set; }
    }
}
